#!/usr/bin/env bash
# Start Apache so as to return a
# page conatining Hello Holberton
service apache2 start
# Check Apache service status
if sudo service apache2 status | grep -q "apache2 is running"; then
    echo "Apache is running"
else
    echo "Apache is not running"
fi

# Query Apache root and check the output
output=$(curl -s http://localhost:8080)
if [[ "$output" == *"Hello Holberton"* ]]; then
    echo "Apache root returns Hello Holberton"
else
    echo "Error: Apache root does not return Hello Holberton"
fi
