#!/usr/bin/env bash

# Start Apache
sudo systemctl start apache2

# Check Apache service status
if sudo systemctl is-active --quiet apache2; then
    echo "Apache2 is running"
else
    echo "Apache2 is not running"
fi

