#!/usr/bin/env bash
# configures a server to listening on port 80 of all server's active IPv4 IPs
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
if sudo service nginx status | grep -q "active (running)"; then
    echo "1"
else
    echo "* nginx is not running"
fi
