#!/usr/bin/env bash

# Modify default configuration (consider creating a separate server block)
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo systemctl restart nginx

#echo "" | sudo dd status=none of=/run/nginx.pid
